# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\client.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.mainFont = QtGui.QFont()
        self.mainFont.setFamily("URW Gothic L")
        self.mainFont.setPointSize(12)
        self.mainFont.setWeight(50)
        self.mainFont.setBold(False)
        self.mainFont.setItalic(False)
        self.mainFont.setUnderline(False)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 799, 559))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 259, 489))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.newContactLE = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.newContactLE.setObjectName("newContactLE")
        self.verticalLayout.addWidget(self.newContactLE)
        self.addContactBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addContactBtn.setObjectName("addContactBtn")
        self.verticalLayout.addWidget(self.addContactBtn)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.conttactsList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.conttactsList.setObjectName("conttactsList")
        self.verticalLayout.addWidget(self.conttactsList)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 519, 489))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sendMsgBtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.sendMsgBtn.setObjectName("sendMsgBtn")
        self.gridLayout_2.addWidget(self.sendMsgBtn, 5, 0, 1, 1)
        self.chatTE = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.chatTE.setObjectName("chatTE")
        self.chatTE.setFont(self.mainFont)
        self.gridLayout_2.addWidget(self.chatTE, 1, 0, 1, 7)

        self.messageTE = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.messageTE.setObjectName("messageTE")
        self.messageTE.setFont(self.mainFont)
        self.gridLayout_2.addWidget(self.messageTE, 4, 0, 1, 7)

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 5, 2, 1, 1)
        self.contactLab = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.contactLab.setStyleSheet("#contactLab {\n"
"    background-color: #A0A0A0;\n"
"}")
        self.contactLab.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contactLab.setIndent(5)
        self.contactLab.setObjectName("contactLab")
        self.gridLayout_2.addWidget(self.contactLab, 0, 0, 1, 7)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setIndent(5)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)

        self.boldBtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.boldBtn.setObjectName("boldBtn")
        self.boldBtn.setIcon(QtGui.QIcon('imgs/b.jpg'))
        self.boldBtn.setIconSize(QtCore.QSize(24,24))
        self.boldBtn.setMaximumWidth(28)
        self.gridLayout_2.addWidget(self.boldBtn, 3, 0, 1, 1)

        self.italicBtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.italicBtn.setObjectName("italicBtn")
        self.italicBtn.setIcon(QtGui.QIcon('imgs/i.jpg'))
        self.italicBtn.setIconSize(QtCore.QSize(24,24))
        self.italicBtn.setMaximumWidth(28)
        self.gridLayout_2.addWidget(self.italicBtn, 3, 1, 1, 1)

        self.underlineBtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.underlineBtn.setObjectName("italicBtn")
        self.underlineBtn.setIcon(QtGui.QIcon('imgs/u.jpg'))
        self.underlineBtn.setIconSize(QtCore.QSize(24,24))
        self.underlineBtn.setMaximumWidth(28)
        self.gridLayout_2.addWidget(self.underlineBtn, 3, 2, 1, 1)

        self.smileBtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.smileBtn.setObjectName("smileBtn")
        self.smileBtn.setIcon(QtGui.QIcon('imgs/smiles/ab.gif'))
        self.smileBtn.setIconSize(QtCore.QSize(24,24))
        self.smileBtn.setMaximumWidth(28)
        self.gridLayout_2.addWidget(self.smileBtn, 3, 3, 1, 1)

        self.sadBtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.sadBtn.setObjectName("sadBtn")
        self.sadBtn.setIcon(QtGui.QIcon('imgs/smiles/ac.gif'))
        self.sadBtn.setIconSize(QtCore.QSize(24,24))
        self.sadBtn.setMaximumWidth(28)
        self.gridLayout_2.addWidget(self.sadBtn, 3, 4, 1, 1)

        self.surprizeBtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.surprizeBtn.setObjectName("surprizeBtn")
        self.surprizeBtn.setIcon(QtGui.QIcon('imgs/smiles/ac.gif'))
        self.surprizeBtn.setIconSize(QtCore.QSize(24,24))
        self.surprizeBtn.setMaximumWidth(28)
        self.gridLayout_2.addWidget(self.surprizeBtn, 3, 5, 1, 1)

        spacerItem2 = QtWidgets.QSpacerItem(1, 200, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 6, 1, 1)



        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 12)
        self.gridLayout_2.setRowStretch(2, 1)
        self.gridLayout_2.setRowStretch(3, 1)
        self.gridLayout_2.setRowStretch(4, 3)
        self.gridLayout_2.setRowStretch(5, 1)
        self.gridLayout.addWidget(self.frame_2, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 785, 30))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.nickLE = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.nickLE.setObjectName("nickLE")
        self.horizontalLayout_2.addWidget(self.nickLE)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.passLE = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.passLE.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passLE.setObjectName("passLE")
        self.horizontalLayout_2.addWidget(self.passLE)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.ipLE = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.ipLE.setEnabled(False)
        self.ipLE.setObjectName("ipLE")
        self.horizontalLayout_2.addWidget(self.ipLE)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.portSpin = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.portSpin.setMinimum(1024)
        self.portSpin.setMaximum(65535)
        self.portSpin.setProperty("value", 7777)
        self.portSpin.setObjectName("portSpin")
        self.horizontalLayout_2.addWidget(self.portSpin)

        self.connectBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.connectBtn.setObjectName("connectBtn")
        self.horizontalLayout_2.addWidget(self.connectBtn)
        
        self.profileBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.profileBtn.setObjectName("profileBtn")
        self.profileBtn.setEnabled(False)
        self.horizontalLayout_2.addWidget(self.profileBtn)



        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        # self.horizontalLayout_2.setStretch(4, 1)
        # self.horizontalLayout_2.setStretch(5, 5)
        # self.horizontalLayout_2.setStretch(6, 1)
        # self.horizontalLayout_2.setStretch(7, 3)
        # self.horizontalLayout_2.setStretch(8, 2)
        self.horizontalLayout_2.setStretch(9, 10)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python CHAT client"))
        self.addContactBtn.setText(_translate("MainWindow", "Добавить контакт"))
        self.sendMsgBtn.setText(_translate("MainWindow", "Отправить"))
        self.contactLab.setText(_translate("MainWindow", "Чат с "))
        self.label_5.setText(_translate("MainWindow", "Ваше сообщение"))
        self.groupBox.setTitle(_translate("MainWindow", "Настройки подключения"))
        self.label_3.setText(_translate("MainWindow", "Имя"))
        self.label_4.setText(_translate("MainWindow", "Пароль"))
        self.label.setText(_translate("MainWindow", "IP"))
        self.ipLE.setText(_translate("MainWindow", "127.0.0.1"))
        self.label_2.setText(_translate("MainWindow", "Port"))
        self.connectBtn.setText(_translate("MainWindow", "Подключиться"))
        self.profileBtn.setText(_translate("MainWindow", "Профиль"))

